apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template: 
    metadata: 
      name: myapp1-pod
      labels:
        app: myapp1       
    spec:
      containers:
        - name: myapp1-container
          image: biswajit59/test-dotnet:12
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"  